package com.pichon.memo.modelo;
// Generated Oct 11, 2018 1:49:03 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Reservations generated by hbm2java
 */
public class Reservations  implements java.io.Serializable {


     private Integer rid;
     private Products products;
     private Users users;
     private Date reserved;

    public Reservations() {
    }

	
    public Reservations(Products products, Users users) {
        this.products = products;
        this.users = users;
    }
    public Reservations(Products products, Users users, Date reserved) {
       this.products = products;
       this.users = users;
       this.reserved = reserved;
    }
   
    public Integer getRid() {
        return this.rid;
    }
    
    public void setRid(Integer rid) {
        this.rid = rid;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Date getReserved() {
        return this.reserved;
    }
    
    public void setReserved(Date reserved) {
        this.reserved = reserved;
    }




}


