package com.pichon.memo.modelo;
// Generated Oct 11, 2018 1:49:03 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer uid;
     private String fname;
     private String lname;
     private String uname;
     private Date dbirth;
     private String email;
     private Set<Reservations> reservationses = new HashSet<Reservations>(0);

    public Users() {
    }

	
    public Users(String fname, String lname, String uname, String email) {
        this.fname = fname;
        this.lname = lname;
        this.uname = uname;
        this.email = email;
    }
    public Users(String fname, String lname, String uname, Date dbirth, String email, Set<Reservations> reservationses) {
       this.fname = fname;
       this.lname = lname;
       this.uname = uname;
       this.dbirth = dbirth;
       this.email = email;
       this.reservationses = reservationses;
    }
   
    public Integer getUid() {
        return this.uid;
    }
    
    public void setUid(Integer uid) {
        this.uid = uid;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getUname() {
        return this.uname;
    }
    
    public void setUname(String uname) {
        this.uname = uname;
    }
    public Date getDbirth() {
        return this.dbirth;
    }
    
    public void setDbirth(Date dbirth) {
        this.dbirth = dbirth;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set<Reservations> getReservationses() {
        return this.reservationses;
    }
    
    public void setReservationses(Set<Reservations> reservationses) {
        this.reservationses = reservationses;
    }




}


